language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lockelamora/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lockelamora/react-test npm test -- --coverage

after_success:
  - docker build -t lockelamora/multi-client ./client
  - docker build -t lockelamora/multi-nginx ./nginx
  - docker build -t lockelamora/multi-server ./server
  - docker build -t lockelamora/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push to docker hub
  - docker push lockelamora/multi-client
  - docker push lockelamora/multi-nginx
  - docker push lockelamora/multi-server
  - docker push lockelamora/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-660282655179
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
